// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML.Transforms.TimeSeries;

namespace Openings_AI
{
    public partial class Openings
    {
        /// <summary>
        /// model input class for Openings.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"opening_ply")]
            public float Opening_ply { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Openings.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"opening_ply")]
            public float[] Opening_ply { get; set; }

            [ColumnName(@"opening_ply_LB")]
            public float[] Opening_ply_LB { get; set; }

            [ColumnName(@"opening_ply_UB")]
            public float[] Opening_ply_UB { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@"D:\Adus Stuff\Coding Stuff\Projects\Visual Studio\Chess Engine\Chess Logic\Openings.zip");

        public static readonly Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput? input = null, int? horizon = null)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input, horizon);
        }

        private static TimeSeriesPredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
            return mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
        }
    }
}

