// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace Openings_AI
{
    class Program
    {
        static void Main(string[] args)
        {
            // predict with default option.
            var modelOutput = Openings.Predict();
            Console.WriteLine(string.Join(",", modelOutput.Opening_ply));

            // predict next 5 periods
            modelOutput = Openings.Predict(horizon: 5);
            Console.WriteLine(string.Join(",", modelOutput.Opening_ply));

            // update and predict model
            // TBD
        }
    }
}

